name: visit-api

service:
  name: visit-api
  type: ClusterIP
  port: 9091

image:
  repository: miroit/visit-api
tag: '9b0bd5a'

replicaCount: 1

global:
  logPath: /root/logs

spring:
  profiles:
    active: dev