name: visit-api

service:
  name: visit-api
  type: ClusterIP
  port: 7001

image:
  repository: miroit/visit-api
tag: 'fc9e3c1'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: local
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs