name: visit-api

service:
  name: visit-api
  type: ClusterIP
  port: 9091

image:
  repository: miroit/visit-api
tag: '68d002f'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: dev
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs