name: hr-api

service:
  name: hr-api
  type: ClusterIP
  port: 9095

image:
  repository: miroit/hr-api
tag: '18bd09a'

replicaCount: 1

global:
  logPath: /root/logs

spring:
  profiles:
    active: dev