apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: miroit-access
  labels:
    service: {{ .Values.name }}
    app: {{ .Values.service.name }}
    release: prometheus-stack
    service_type: server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8081
    - name: docker-registry
      port: 12000
      protocol: TCP
      targetPort: 12000
  selector:
    app: {{ .Values.service.name }}
  sessionAffinity: None
  type: ClusterIP