name: frontend-template

service:
  name: frontend-template
  type: ClusterIP
  port: 3000

image:
  repository: pachipico/frontend-template
tag: 'latest'

replicaCount: 1

global:
  logPath: /root/logs