name: example

service:
  name: example
  type: ClusterIP
  port: 8080

image:
  repository: miroit/example
tag: '73bd81c'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: local
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs