name: config-server

service:
  name: config-server
  type: ClusterIP
  port: 8888

image:
  repository: miroit/config-server
tag: '0359a42'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: local
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs

env:
  - name: GIT_USERNAME
    valueFrom:
      secretKeyRef:
        name: github-auth
        key: username
  - name: GIT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: github-auth
        key: password