name: gateway

service:
  name: gateway
  type: ClusterIP
  port: 9000

image:
  repository: miroit/gateway
tag: '3ab6006'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: local
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs