name: gateway

service:
  name: gateway
  type: ClusterIP
  port: 9000

image:
  repository: miroit/gateway
tag: '7f3f100'

replicaCount: 1

global:
  logPath: /root/logs

spring:
  profiles:
    active: dev