{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolume*/}}
{{/*metadata:*/}}
{{/*  name: alertmanager-pv*/}}
{{/*  labels:*/}}
{{/*    type: local*/}}
{{/*spec:*/}}
{{/*  storageClassName: hostpath*/}}
{{/*  capacity:*/}}
{{/*    storage: 2Gi*/}}
{{/*  accessModes:*/}}
{{/*    - ReadWriteOnce*/}}
{{/*  hostPath:*/}}
{{/*    path: "/mnt/alertmanager"*/}}