apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-templates
data:
  miro.tmpl: |
    {{ define "miro.template" }}
      *[{{ .Status | upper }}]*: {{ .CommonLabels.alertname }}

    {{ range .Alerts }}
    • 인스턴스: {{ .Labels.instance }}
    • 서비스: {{ .Labels.service }}
    • HTTP 상태 코드: {{ .Labels.http_status_code }}
    • 설명: {{ .Annotations.summary }}
    {{ end }}
    {{ end }}