
{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolume*/}}
{{/*metadata:*/}}
{{/*  name: grafana-pv*/}}
{{/*  labels:*/}}
{{/*    type: local*/}}
{{/*spec:*/}}
{{/*  storageClassName: hostpath*/}}
{{/*  capacity:*/}}
{{/*    storage: 10Gi*/}}
{{/*  accessModes:*/}}
{{/*    - ReadWriteOnce*/}}
{{/*  hostPath:*/}}
{{/*    path: "/root/grafana"*/}}
