name: miroit-access

service:
  name: miroit-access
  type: ClusterIP
  port: 80

image:
  repository: miroit/miroit-access
tag: '46c8b36'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: local
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs