name: miro-access

service:
  name: miro-access
  type: ClusterIP
  port: 3000

image:
  repository: miroit/miro-access
tag: 'latest'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: local
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs