name: approval-api

service:
  name: approval-api
  type: ClusterIP
  port: 9094

image:
  repository: miroit/approval-api
tag: 'b6dd8b9'

replicaCount: 1

global:
  logPath: /root/logs

spring:
  profiles:
    active: dev