name: approval-api

service:
  name: approval-api
  type: ClusterIP
  port: 9094

image:
  repository: miroit/approval-api
tag: 'cfa2fa3'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: dev
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs