name: miroit-access-fe

service:
  name: miroit-access-fe
  type: ClusterIP
  port: 80

image:
  repository: miroit/miroit-access-fe
tag: '18a6e7e'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: local
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs