name: content-api

service:
  name: content-api
  type: ClusterIP
  port: 9092

image:
  repository: miroit/content-api
tag: '9b5e5a0'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: dev
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs