name: content-api

service:
  name: content-api
  type: ClusterIP
  port: 9092

image:
  repository: miroit/content-api
tag: '025d20f'

replicaCount: 1

global:
  logPath: /root/logs

spring:
  profiles:
    active: dev