name: content-api

service:
  name: content-api
  type: ClusterIP
  port: 9092

image:
  repository: miroit/content-api
tag: '14b0f46'

replicaCount: 1

global:
  logPath: /root/logs
  filePath: /root/uploaded_files

spring:
  profiles:
    active: dev