name: file-server

service:
  name: file-server
  type: ClusterIP
  port: 9092

image:
  repository: miroit/file-server
tag: '025d20f'

replicaCount: 1

global:
  logPath: /root/logs
  filePath: /root/uploaded_files

spring:
  profiles:
    active: dev