name: notification-api

service:
  name: notification-api
  type: ClusterIP
  port: 9093

image:
  repository: miroit/notification-api
tag: 'ecb7231'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: dev
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs