name: notification-api

service:
  name: notification-api
  type: ClusterIP
  port: 9093

image:
  repository: miroit/notification-api
tag: 'f269e30'

replicaCount: 1

global:
  logPath: /root/logs

spring:
  profiles:
    active: dev