name: miroit-nexus

service:
  name: miroit-nexus
  type: ClusterIP
  port: 80

image:
  repository: sonatype/nexus3:3.81.1
tag: '3.81.1-alpine'

replicaCount: 1

global:
  #  configMapName: dev-configmap
  activeProfile: local
  #  discoveryUrl: http://spring-cloud-kubernetes-discoveryserver:80
  logPath: /root/logs